plugins {
    id 'com.android.application'
}

android {
    namespace 'digital.blacktech.obd'
    compileSdk 34

    defaultConfig {
        applicationId 'digital.blacktech.obd'
        minSdk 26
        targetSdk 34
        versionCode (System.getenv('GITHUB_RUN_NUMBER') ?: '1').toInteger()
        versionName "1.0." + (System.getenv('GITHUB_RUN_NUMBER') ?: '0')
    }

    signingConfigs {
        release {
            storeFile file('release.keystore')
            storePassword 'obd12345'
            keyAlias 'obd'
            keyPassword 'obd12345'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
